`numpy` 的 `Ndarray` 对象是一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组。
作为同构数据多维容器,`Ndarray`中的所有元素必须是相同类型

它可以执行对整组数组进行快速的直接运算,而不用写循环.类似于C/C++


In [10]:
from numpy import * #导入模块,仅在示例中使用,平常不推荐导入全部对象

In [61]:
list_a = ([1,2,3],[4,5,6],[7,8,9])
print (list_a)
array(list_a)

([1, 2, 3], [4, 5, 6], [7, 8, 9])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a = array([1,2,3])
a

array([1, 2, 3])

In [7]:
a = a + 1 #可直接对array操作
a

array([2, 3, 4])

In [8]:
a*a

array([ 4,  9, 16])

`np.array`会尝试为新建的这个数组推断出一个较为合适的数据类型。数据类型保存在一个特殊的`dtype`对象中。

In [30]:
b = array([[1,3,2],['c','d','e']]) #当出现不同类型时,会默认一个类型
b

array([['1', '3', '2'],
       ['c', 'd', 'e']], dtype='<U11')

In [32]:
b = array([[1,'2',3],[3,2,1]]) 
b

array([['1', '2', '3'],
       ['3', '2', '1']], dtype='<U11')

In [34]:
c = array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
c.dtype  #查看array类型

dtype('int32')

In [39]:
c.shape #表示各维度数值大小的元祖

(2, 3)

In [40]:
c.ndim #输出维度

2

除`np.array`之外，还有一些函数也可以新建数组。比如，`zeros`和`ones`分别可以创建指定长度或形状的全0或全1数组。`empty`可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需传入一个表示形状的元组即可：

> Wes McKinney. 利用Python进行数据分析 (O'Reilly精品图书系列) (Kindle 位置 1666-1667). 机械工业出版社. Kindle 版本. 

In [63]:
zeros(10,bool)

array([False, False, False, False, False, False, False, False, False,
       False])

In [86]:
ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
#创建多维数组需要给参数传递一个元祖
empty((6,2,3)) #多数情况下返回未初始化的垃圾值

array([[[1.39804066e-076, 1.18295070e-076, 3.44353309e-086],
        [4.01647309e-057, 6.03105902e-154, 3.31186189e-033]],

       [[4.42415339e-062, 6.01347002e-154, 8.09244594e-153],
        [3.31186189e-033, 4.42415339e-062, 1.39736982e-076]],

       [[1.21089429e-099, 4.56335221e-072, 4.28007249e-033],
        [5.46819512e-095, 6.01347002e-154, 4.56360677e-072]],

       [[4.28007249e-033, 1.05162547e-153, 1.03118977e-071],
        [7.11326537e-067, 1.30371153e-076, 2.62395837e+179]],

       [[1.03105904e-259, 2.25563609e-153, 3.29370568e+180],
        [5.86679289e+276, 3.74165229e+233, 1.02420533e-259]],

       [[2.25563609e-153, 9.13544126e+242, 4.62882726e-072],
        [1.05089594e-153, 5.98149210e-154, 6.01347002e-154]]])

In [47]:
arange(15) #返回range的数组板

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

由于NumPy关注的是数值计算，因此，如果没有特别指定，数据类型基本都是float64（浮点数）。

> Wes McKinney. 利用Python进行数据分析 (O'Reilly精品图书系列) (Kindle位置1679). 机械工业出版社. Kindle 版本. 

`asarray`与`array`的区别:当数据源是ndarray时，array仍然会copy出一个副本，占用新的内存，但asarray不会。
 也就是说用`array`去转换`ndarray`数组,会将原数据复制到新的内存中,新的地址.asarray则指向原来的位置
 eg:https://blog.csdn.net/gobsd/article/details/56485177

创建对角线为1的NxN 矩阵

In [81]:
eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])